import './style.css';
// import './topics/01-basic-types';
//import './topics/02-object-interface';
//import './topics/03-funtions';
//import './topics/04-homework-types';
//import './topics/05-basic-detructuring';
//import './topics/06-functions-destructuring';
//import './topics/07-modules';
//import './topics/08-clases';
//import './topics/09-generic';
//import './topics/10-decorators';
import './topics/11-optional-chaining';
const main = document.getElementById('app')!;
main.innerHTML = '<h1>NEIRA CHCHUTMARE</h1>';
